### ISSUE TITLE
Enable Django REST Framework default API portal

### ISSUE THREAD

**Issue by brylie** [codebuddies/django-concept#32]
Django REST Framework (DRF) will auto-generate a [browsable API portal](https://www.django-rest-framework.org/topics/browsable-api/) for developers to quickly try out API endpoints. This API UI helps developers to quickly experiment with the API.

## Task
- [ ] Enable DRF browsable API UI

**Comment by BethanyG** [comment]
This is also already completed via issue-20, issue-24 and others.  The master branch is not up to date.  Please see the other issues in this repo for details.

**Comment by brylie** [comment]
Ok. Is there a related pull request?

**Comment by BethanyG** [comment]
CORRECTION:  While `issue-20` and `issue-24` do have the most up-to-date code for JWT, etc.  The browsable API is already active by default even in master.  So this should already be available.

**Comment by brylie** [comment]
Ah, I couldn't access the API interface. What is the route?

**Comment by BethanyG** [comment]
Since tests are still in process (_hence so is the PR_), please use https://github.com/BethanyG/django-concept/tree/issue-24/cbv3_django_prototype.  That brach includes both fixtures for `Users` and `Resources`, as well as JWT auth code.  

Viewing `Resources` requires a Token.  The easiest way to get one saved in your browser session is to visit `/auth/obtain_token/` and fill in the username and password of a user in the system.  Once it hands back a token, you should be good to go.

You should then be able to hit the "browsable api" for `Resources` via  `http://127.0.0.1:8000/api/v1/resources/`, which should return all resources from the `Resources` fixture, if you've loaded it.   Pressing the [options] button in the browser will give you a JSON list of required/not required fields.  Scrolling down will give you and HTML form for making POSTs.  Pressing the [filters] button will allow a simple text search on all "searchable" fields.  Dynamic search is a WIP for another PR.
