### ISSUE TITLE
Frontend will be in React, Delete Templates and use Django API only?

### ISSUE THREAD

**Issue by sebbel** [codebuddies/django-concept#57]
So right now we have the split between frontend and backend, would it make sense to explicitly delete templates and defer frontend work to codebuddies/react-concept?

**Comment by jesperhodge** [comment]
@sebbel I work professionally on a big Rails + React app. The way we did it - which seems to make most sense to me - is we removed the templates, after all they prevent you from having a single-page app. There are two ways you can go then, either really fullout API-only, or do it partially and keep maybe a layout file into which you render React, and then keep all the Backend-specific tooling like session cookie handling for authentication and routing and so on in place. That's the way we did it, which I think takes care of a lot of problems. But I definitely suggest to remove views / templates and stuff for specific pages.

As for routing: You have routing inside of React of course, but you probably also will want to keep all the Django backend routing as well for better security, so any route not explicitly defined will always give a 404 independently of what happens in the frontend.

**Comment by sebbel** [comment]
i dont know too much on django, is it suitable for api-only?

**Comment by jesperhodge** [comment]
I have no idea, I need to learn django. (Not too much of a problem as I know Ruby/Rails and Python). There is https://www.django-rest-framework.org/ (and surely many similar projects exist) which apparently works on top of Django, that might be an easy solution. In any case, somehow integrating at least some kind of endpoint for React into this project should be necessary to go ahead, as the whole architecture depends on how this is done. If you want to integrate the React frontend into the Django `base.html` directly, you may need to move the whole React frontend into this project and maybe even bundle it here with webpack and even not use `create-react-app`. So the more I think about it the more I prefer the idea of having this api-only and having everything including the entry index html file in the frontend project to avoid all those problems.

**Comment by jesperhodge** [comment]
As far as I remember Django facilitates a nice admin backend to manage your resources. It might be an idea just to have that as a normal Python-rendered html view, if the slow non-SPA aspect does not bother you. Just to save work. And then have the user-facing frontend as a React SPA app. I don't know if that works, but if so that can be changed later on easily.

**Comment by brylie** [comment]
Yeah, I'm in favor of using Django templates to the extent possible. We lose too much (simplicity) by going full SPA, in my opinion, like having cohesion of templating, routing, and the data model that Django provides (a.k.a. "batteries included"). Projects can get quite far with fairly standard HTML, CSS, Django templates, and then sprinkle in some JavaScript (AJAX) where it is useful.

The article [Iterating with Simplicity](https://engineering.instawork.com/iterating-with-simplicity-evolving-a-django-app-with-intercooler-js-8ed8e69d8a52) describes a fairly interesting approach to adding dynamic page elements. It sits at a comfortable medium between serving static, server-rendered pages and having a full SPA.

People have taken the SPA concept full-circle and landed back on server-side rendering, and lost out on having a mature backend framework (like Rails or Django) in the process.

**Comment by jesperhodge** [comment]
Well I just heard that the frontend is intended to be a separate project as it is, so that means the backend can only provide an API anyway. As far as I see it that answers the question posed by this issue with a clear and simple "Yes". Maybe a code owner who is familiar with the Django part can confirm this and we close this issue and start implementing? :) (Please correct me if I am mistaken.)

**Comment by lpatmo** [comment]
> So right now we have the split between frontend and backend, would it make sense to explicitly delete templates and defer frontend work to codebuddies/react-concept?

@sebbel We definitely don't need the templates in the Django app as user-facing pages, but I don't think we need to delete them either. They're useful to click around in dev (e.g. if I want to create a new user without running a `createsuperuser` command), and the home page with the "tips for Django API contributors" (that base.html file you worked on in PR #54) is great for someone to see when they're running the app. 

> People have taken the SPA concept full-circle and landed back on server-side rendering, and lost out on having a mature backend framework (like Rails or Django) in the process.

I _hope_ this doesn't happen to us, but if so -- it would be an interesting learning experience 😂 Thanks for the share to https://engineering.instawork.com/iterating-with-simplicity-evolving-a-django-app-with-intercooler-js-8ed8e69d8a52, btw -- an interesting read! 

> Maybe a code owner who is familiar with the Django part can confirm this and we close this issue and start implementing?

And yes -- can confirm that we're using Django Rest Framework (@BethanyG did a bunch of work setting up user authentication endpoints and a `/resources` endpoint in https://github.com/codebuddies/django-concept/pull/42 and https://github.com/codebuddies/django-concept/pull/8) with a React frontend in github.com/codebuddies/react-concept which will feed from it, eventually. (The react app currently has a local "fake" json DB.)

> It would actually be really nice then to open an issue to integrate these two projects for routing and api calls, so we can see how everything works together.

This will be accomplished once we have our Django app running in production with a production database. But until then, I think we can continue mocking the calls to the API in the React app and iterate on the UX so that we know for sure what we need in the JSON responses, before we do too much work having to push changes to the production Django app. 

====
@jesperhodge Sorry that some of the core "this is what we're building and hooking up" wasn't clear in the READMEs; let me know if you have other questions! Otherwise, agree this issue can probably be closed out.

**Comment by BethanyG** [comment]
We are indeed using DRF (Django Rest Framework) for the REST API endpoints that the front end react application will feed from.  However, we have also kept the core Django user management, profiles, and admin interface.  We've added JWT auth.

As @lpatmo has pointed out, using DRF but retaining core Django features allows us to have a built-in and relatively easy to customize administrative interface for user levels and db administration.  This allows us for example to create users that could enter or edit resources in an easy fashion without having to resort to writing a script, or making a custom set of Admin pages in React.  We may also decide down the road that there are sections of the site that might be easier to render as more traditional Django apps - either for speed or for prototyping or other purposes.  It doesn't all have to be a SPA.

I am still working on  issue #43, so the code as is in the reop doesn't function for returning resources via DRF and the DB model is not accurate. I'm hoping to wrap the work soon-ish and can do a hangout for anyone interested in what I've got so far, and what would need to happen for next steps in implementation for `resources`.  If anyone would like to help me with that (_I am a bit stuck on the incoming serializer_), I'd welcome collaborators.

That being said, `resources` is only one endpoint and we have many others.  So there's a lot of work that can be done in adding additional endpoints, and thinking through how endpoints relate to one another.  This was not kept up to date, but here is an ERD that we worked on last year for the project:  
![10_05_2019 Backup CBV3 ERD (1)](https://user-images.githubusercontent.com/5923094/73613718-317a9f80-45ad-11ea-83a2-2e72c847d656.png).  

In particular
* what sorts of search methodologies do we want to use (_do we implement our own search through Django and Postgres, or do we plug in something?_), 
* how do we connect these entities relationally (_or do we?_)
* what do the JSON specs look like for specific endpoints (hangouts, user_profiles, notes, discussions, learning_paths) 

are all areas we still need to figure out.

**Comment by lpatmo** [comment]
Thank you for the notes/update, @BethanyG! 

>  If anyone would like to help me with that (I am a bit stuck on the incoming serializer), I'd welcome collaborators.
Is there any chance you can jot down some notes in #43 about how to replicate the issues you're having with the serializer (e.g. which branch we should check out)? If it's faster to pair on this, happy to do so -- though admittedly I _hope_ I can help, since my experience with DRF serializers is limited. 

> what sorts of search methodologies do we want to use (do we implement our own search through Django and Postgres, or do we plug in something?),
how do we connect these entities relationally (or do we?)
what do the JSON specs look like for specific endpoints (hangouts, user_profiles, notes, discussions, learning_paths)

Good questions -- I'm not sure about 1 or 2 (maybe we should discuss this inside an issue), but as for 3, hoping to work that out while mocking out the UI/front-end starting with https://github.com/codebuddies/react-concept/issues/52.

**Comment by billglover** [comment]
This sounds like we've arrived at a decision to retain the template pages (for now). I'm going to close this issue and suggest we revisit if we find that the admin pages are becoming an unnecessary overhead.

**Comment by tgrrr** [comment]
Late to the table, but
I'm actually against templates, because imho it creates problems for passing state between react components in different templates.

**Comment by lpatmo** [comment]
@tgrrr Ah, to clarify -- we're not going to be using Django templates at all for the purposes of our app, which will be Django API + React frontend. I haven't written Django templates + React inside the templates before, but that makes sense. :)

**Comment by tgrrr** [comment]
Thanks for clarifying. How are we going to do it?

**Comment by lpatmo** [comment]
@tgrrr The Django API will be deployed separately on DigitalOcean as `api.codebuddies.org/v1/etc.`, and the React front-end will be deployed on Netlify, which we have a sponsored open source license with. 

The React app will be making requests to the API. 

Not sure if that's what you were asking about -- let me know if I answered your question!
